# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: stemsama <stemsama@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/16 11:37:09 by stemsama          #+#    #+#              #
#    Updated: 2023/03/02 17:49:17 by stemsama         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC = cc
FLAGS =  -Wall -Werror -Wextra

SRC = ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_strlen.c ft_isalpha.c ft_isdigit.c ft_isalnum.c \
				ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_strlcpy.c ft_strlcat.c ft_strnstr.c \
				ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_split.c ft_itoa.c ft_putchar_fd.c ft_strtrim.c \
				ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_striteri.c ft_strmapi.c 		
OBJECT = $(SRC:.c=.o)


BONUSC = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c\
		ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c\
		ft_lstclear.c ft_lstiter.c
OBJECT_BONUS = $(BONUSC:.c=.o)


all : $(NAME)

$(NAME) : $(OBJECT)
	@ar -cr $(NAME) $(OBJECT)
	
bonus : $(OBJECT_BONUS)
	@ar -cr $(NAME) $(OBJECT_BONUS)

%.o:%.c libft.h
	@$(CC) $(FLAGS) -c $< -o $@ 

clean :
	@rm -f $(OBJECT) $(OBJECT_BONUS)

fclean : clean
	@rm -f $(NAME)

re : fclean all

.PHONY: clean fclean re all
